config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'top', to: 'homes#top'
  get 'terms', to: 'homes#terms'

  resources :guests, only: %i[index new]

  get 'signup', to: 'users#new'
  resources :users, only: %i[create]
  resource :profile, only: %i[show edit update destroy] do
    get 'cancel'
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :searches, only: %i[index new create]
  resources :departures
  root 'departures#new'
  resources :destinations, only: %i[new create show edit update destroy]
  resources :histories, only: %i[new create show edit update destroy] do
    get 'cancel', on: :member
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def show
    @one_week_moving_distances = History.one_week_moving_distances(current_user)
    @histories = current_user.histories.finished_list
    @total_moving_time = 0
    @histories.each { |history| @total_moving_time += ((history.end_time - history.start_time) / 60).to_i }
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash.now[:success] = 'ユーザー情報を更新しました'
      render turbo_stream: turbo_stream.replace('profile', partial: 'profile')
    else
      flash.now[:error] = '入力情報に誤りがあります'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    redirect_to signup_path, flash: { success: 'ユーザーを削除しました' }, status: :see_other
  end

  def cancel; end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/views/profiles/_history.html.erb
<%= turbo_frame_tag "history_#{history.uuid}" do %> <%# profile#showにて、1つ1つに割り振る用 %>
  <div class="info-card pb-0 keep-all zen-kaku-regular">
    <%= render 'shared/toast' if is_turbo_frame_request? %> <%# history#update成功用 %>

    <div class="text-left mb-1 lg:mb-0 text-gray-700 tracking-tighter">
      <p class="mr-0 lg:mr-3 block lg:inline-block">
        <%= fa_icon 'home' %>
        <%= history.destination.departure.name %>
      </p>

      <p class="block lg:inline-block">
        <%= fa_icon 'clock-o' %>
        <%= l(history.start_time, format: :short) %>
        <span class="ml-1"><%= history.decorate.moving_time %>分</span>
      </p>
    </div>

    <div class="text-gray-800 text-2xl lg:text-3xl zen-kaku-medium">
      <h5 class="mr-0 lg:mr-5 block lg:inline-block">
        <%= fa_icon 'flag' %>
        <%= history.destination.name %>
      </h5>
      <h5 class="block lg:inline-block">
        <%= fa_icon 'road' %>
        <%= history.moving_distance %>m
      </h5>
    </div>

    <p class="text-gray-700 tracking-tighter">
      <%= history.destination.address %>
    </p>

    <div class="text-gray-800 tracking-tighter mt-0.5 mb-3">
      <% if history.comment %>
        <p>
          <%= fa_icon 'eye-slash' %>
          <%= fa_icon 'commenting' %>
          <%= history.comment %>
        </p>
      <% end %>
    </div>

    <div>
      <%= link_to '出発', new_history_path(destination: history.destination.uuid),
      data: { turbo_frame: '_top' },
      class: 'orange-btn tracking-widest text-xl px-12 py-2 zen-kaku-medium' %>
    </div>

    <div data-controller="dropdown">
      <%= render 'shared/dropdown' %>

      <div class="mb-3 hidden" data-dropdown-target="menu">
        <%= link_to '編集', edit_history_path(history.uuid, route: 'profile_page'),
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular mr-4' %>

        <%= link_to '削除', history_path(history.uuid, route: 'profile_page'),
        data: { turbo_method: :delete, turbo_confirm: "履歴から削除します\nよろしいですか?"},
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular border-red-600 text-red-600' %>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<%= turbo_frame_tag 'profile' do %> <%# profile#editと入れ替わる用 %>
  <%= render 'shared/toast' if is_turbo_frame_request? %> <%# profile#update成功用 %>

  <div class="zen-kaku-medium text-xl lg:text-2xl p-2 flex justify-center text-center">
    <%= link_to '編集', edit_profile_path, class: 'text-green-600 underline w-2/5' %>

    <%= link_to 'ログアウト', logout_path,
    data: { turbo_method: :delete, turbo_frame: '_top', turbo_confirm: 'ログアウトしますか？' },
    class: 'text-red-600 underline w-2/5' %>
  </div>

  <div data-controller="dropdown">
    <%= render 'shared/dropdown' %>

    <div class="mb-3 hidden text-center" data-dropdown-target="menu">
      <%= link_to 'ユーザー削除', profile_path,
      data: { turbo_method: :delete, turbo_frame: '_top', turbo_confirm: "データは全て削除され、戻すことはできません。\n削除しますか？" },
      class: 'zen-kaku-medium block text-red-900 underline inline' %>
    </div>
  </div>
<% end %>

app/views/profiles/cancel.html.erb
<div class="info-card pb-0 keep-all zen-kaku-regular">
  <%= render 'profile' %>
</div>

app/views/profiles/edit.html.erb
<div class="basic-card zen-kaku-regular">
  <%= turbo_frame_tag 'profile' do %> <%# profile#showと入れ替わる用 %>
    <%= render 'shared/toast' if is_turbo_frame_request? %> <%# profile#updateのバリデーションエラー用 %>

    <%= form_with model: @user, url: profile_path, class: 'zen-kaku-medium' do |f| %>
      <div class="my-5 text-left">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'normal-form' %>
        <%= render partial: 'shared/error_message', collection: @user.errors.full_messages_for(:name) %>
      </div>

      <div class="my-5 text-left">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'normal-form' %>
        <%= render partial: 'shared/error_message', collection: @user.errors.full_messages_for(:email) %>
      </div>

      <div class="my-5 text-right zen-kaku-regular text-xl tracking-wider">
        <%= link_to '取消', cancel_profile_path, class: 'border-orange-btn px-5 py-2' %>
        <%= f.submit '更新', class: 'orange-btn px-5 py-2.5' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, 'プロフィール') %>

<div class="basic-card">
  <div class="chart-area" data-controller="chart" data-chart-distance-value=<%= @one_week_moving_distances.to_s.delete(' ') %>>
      <canvas id="myChart"></canvas>
  </div>

  <div class="info-card">
    <p class="text-xl tracking-widest zen-kaku-medium underline decoration-cyan-600">
      <%= "#{@user.name}さん" %>
    </p>

    <div class="mt-3 text-gray-800 text-2xl lg:text-3xl tracking-wider zen-kaku-medium">
      <h5 class="block lg:inline-block ml-0 lg:ml-4 underline decoration-double decoration-sky-600">
        <%= "総移動時間: #{@histories.sum {|history| history.decorate.moving_time}}分" %>
      </h5>

      <h5 class="block lg:inline-block mt-1 lg:mt-0 underline decoration-double decoration-teal-600">
        <%= "総移動距離: #{@histories.sum(:moving_distance)}m" %>
      </h5>
    </div>
  </div>
</div>


<div class="tabs mt-4">
  <input id="left" type="radio" name="tab-radio-button" checked>
  <label class="tab-item w-1/2 zen-kaku-medium text-xl tracking-widest" for="left">
    <%= fa_icon 'history', class: 'text-2xl' %>
    <p class="inline-block">履歴</p>
  </label>

  <input id="right" type="radio" name="tab-radio-button">
  <label class="tab-item w-1/2 zen-kaku-medium text-xl tracking-widest" for="right">
    <%= fa_icon 'gear', class: 'text-2xl' %>
    <p class="inline-block">設定</p>
  </label>

  <div class="tab-content" id="left-content">
    <%= render partial: 'history', collection: @histories %>
  </div>

  <div class="tab-content relative" id="right-content">
    <%= render 'profile' %>
  </div>
</div>