config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'top', to: 'homes#top'
  get 'terms', to: 'homes#terms'

  resources :guests, only: %i[index new]

  get 'signup', to: 'users#new'
  resources :users, only: %i[create]
  resource :profile, only: %i[show edit update destroy] do
    get 'cancel'
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :searches, only: %i[index new create]
  resources :departures
  root 'departures#new'
  resources :destinations, only: %i[new create show edit update destroy]
  resources :histories, only: %i[new create show edit update destroy] do
    get 'cancel', on: :member
  end
end

app/views/shared/_dropdown.html.erb
<div class="flex flex-row-reverse text-gray-500">
  <div class="p-1" data-action="click->dropdown#openOrClose" data-dropdown-target="openButton">
    <%= fa_icon "chevron-down"%>
  </div>
  <div class="p-1 hidden" data-action="click->dropdown#openOrClose" data-dropdown-target="closeButton">
    <%= fa_icon "chevron-up" %>
  </div>
</div>

app/views/shared/_error_message.html.erb
<p class="text-red-600"><%= error_message %></p>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="bg-blue-100 border-b border-blue-500 text-blue-700 px-4 py-3 text-lg">
    <p class="zen-kaku-medium inline-block"><%= notice %></p>
    <%= link_to 'こちら', history_path(@not_finished_history.uuid), class: 'zen-kaku-regular underline ml-2' if @not_finished_history %>
  </div>
<% elsif flash[:alert] %>
  <div class="bg-red-100 border-b border-red-500 text-red-700 px-4 py-3 text-lg">
    <p class="zen-kaku-medium"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-cyan-800 py-6 lg:py-12 pl-4">
  <ul class="text-gray-100 flex flex-col lg:flex-row justify-center items-center">
    <li class="mb-4 lg:mb-0 lg:mr-12">
      <%= link_to '利用規約', terms_path %>
    </li>
    <li class="mb-4 lg:mb-0 lg:mr-12">
      <%= link_to 'プライバシーポリシー', 'https://kiyac.app/privacypolicy/MJIjHojL1fFp8ok7HOLL' %>
    </li>
    <li class="mb-4 lg:mb-0 lg:mr-12">
      <%= link_to 'お問い合わせ', 'https://twitter.com/KoukiGyunyu' %>
    </li>
  </ul>
</div>

app/views/shared/_header.html.erb
<nav class="fixed top-0 w-full bg-cyan-600 text-gray-100 drop-shadow-xl z-10 px-2 sm:px-8">
  <div class="flex items-center justify-between tracking-tighter lg:tracking-wider">
    <%= link_to "Today's Course", top_path,
    class: 'text-2xl lg:text-3xl zen-kaku-bold py-4' %>

    <div class="text-lg lg:text-xl zen-kaku-medium mt-1">
      <% if request.fullpath != signup_path && !(request.post? && request.fullpath == users_path) %>
        <%= link_to '新規登録', signup_path,
        class: 'mx-0.5 lg:mx-1.5',
        data: { turbo_frame: '_top' } %>
      <% end %>

      <% if request.fullpath != login_path && !(request.post? && request.fullpath == login_path) %>
        <%= link_to 'ログイン', login_path,
        class: 'mx-0.5 lg:mx-1.5',
        data: { turbo_frame: '_top' } %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navigation_bar.html.erb
<table class="w-screen bg-gray-900 text-white fixed bottom-0 table-fixed z-10 nav-height">
  <tbody>
    <tr>
      <td>
        <%= link_to new_departure_path, class: 'block h-full relative', data: { turbo_frame: '_top' } do %>
          <%= fa_icon 'search', class: 'nav-icon' %>
        <% end %>
      </td>
      <td class="border-x-2">
        <%= link_to departures_path, class: 'block h-full relative', data: { turbo_frame: '_top' } do %>
          <%= fa_icon 'folder-open', class: 'nav-icon' %>
        <% end %>
      </td>
      <td>
        <%= link_to profile_path, class: 'block h-full relative' do %>
          <%= fa_icon 'user', class: 'nav-icon' %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/shared/_toast.html.erb
<% if flash? %>
  <% flash.each do |type, messages| %>
    <% if messages.instance_of?(Array) %>
      <% messages.each do |message| %>
        <div  data-controller="toast"
              data-toast-type-value=<%= type %>
              data-toast-message-value=<%= message %>>
        </div>
      <% end %>
    <% else %>
      <div  data-controller="toast"
            data-toast-type-value=<%= type %>
            data-toast-message-value=<%= messages %>>
      </div>
    <% end %>
  <% end %>
<% end %>