config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'top', to: 'homes#top'
  get 'terms', to: 'homes#terms'

  resources :guests, only: %i[index new]

  get 'signup', to: 'users#new'
  resources :users, only: %i[create]
  resource :profile, only: %i[show edit update destroy] do
    get 'cancel'
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :searches, only: %i[index new create]
  resources :departures
  root 'departures#new'
  resources :destinations, only: %i[new create show edit update destroy]
  resources :histories, only: %i[new create show edit update destroy] do
    get 'cancel', on: :member
  end
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :destination
  has_one :departure, through: :destination

  validates :comment, length: { maximum: 255 }
  validates :moving_distance, presence: true, numericality: { only_integer: true, in: 1..42_195 }
  validates :start_time, presence: true, on: :update
  validates :end_time, presence: true, on: :update
  validate :start_time_check, on: :create
  validate :end_time_check

  before_create -> { self.uuid = SecureRandom.uuid }
  before_create -> { self.start_time = Time.zone.now if start_time.nil? }
  before_create -> { self.comment = nil if comment.blank? }

  before_update -> { self.comment = nil if comment.blank? }

  scope :with_location, -> { includes(destination: [:location, { departure: :location }]) }
  scope :not_finished, -> { where(end_time: nil) }
  scope :finished, -> { where.not(end_time: nil) }
  scope :recent, -> { order(start_time: :desc) }
  scope :past_week, -> { where(start_time: Time.zone.today.ago(6.days)..Time.zone.today.end_of_day) }

  scope :list, -> { with_location.recent }
  scope :finished_list, -> { finished.with_location.recent }

  def self.create_with_location(user, departure_info, destination_info, course)
    if destination_info[:uuid]
      destination = user.destinations.find_by!(uuid: destination_info[:uuid])
    else
      destination = Destination.create_with_location(user, departure_info, destination_info)
    end

    if course == 'round_trip'
      moving_distance = destination_info[:distance] * 2
    else
      moving_distance = destination_info[:distance]
    end

    user.histories.create!(destination:, moving_distance:)
  end

  def self.one_week_moving_distances(user)
    one_week_histories = user.histories.past_week
    week = (0..6).to_a.map { |i| Time.zone.now - i.days }
    week.reverse.map do |day|
      one_day_histories = one_week_histories.find_all { |hitory| day.all_day.cover?(hitory.start_time) }
      one_day_histories.sum(&:moving_distance)
    end
  end

  private

  def start_time_check
    errors.add(:start_time, 'を入力してください') if start_time.nil? && end_time
  end

  def end_time_check
    return unless start_time && end_time

    errors.add(:end_time, 'は開始時刻より遅い時間にしてください') if start_time > end_time
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :check_course_params, only: %i[create]
  before_action :check_and_set_departure_info_from_session, only: %i[create]
  before_action :check_and_set_destination_info_from_session, only: %i[create]
  before_action :set_history, only: %i[show edit update destroy cancel]
  before_action :set_route, only: %i[edit update destroy cancel]

  skip_before_action :check_not_finished, only: %i[show]

  def show
    @departure_info = @history.departure.attributes_for_session
    @destination_info = @history.destination.attributes_for_session
    gon.locationInfo = { departure: @departure_info, destination: @destination_info }
  end

  # destinations#newから遷移の場合、turbo_frameリクエスト
  def new
    destination = current_user.destinations.find_by(uuid: params[:destination])
    session[:destination] = destination.attributes_for_session if destination
    return if check_and_set_destination_info_from_session

    destination ||= current_user.destinations.find_by(uuid: @destination_info[:uuid])
    session[:departure] = destination.departure.attributes_for_session if destination
    return if check_and_set_departure_info_from_session

    gon.locationInfo = { departure: @departure_info, destination: @destination_info }
  end

  def edit; end

  def create
    history = History.create_with_location(current_user, @departure_info, @destination_info, params[:course])

    if params[:course] == 'round_trip'
      flash[:success] = 'スタートしました(往復)'
    else
      flash[:success] = 'スタートしました(片道)'
    end

    redirect_to history_path(history.uuid)
  end

  def update
    unless @history.end_time
      @history.update!(end_time: Time.zone.now)
      return redirect_to history_path(@history.uuid), flash: { success: 'ゴールしました' }, status: :see_other
    end

    if @history.update(history_params)
      flash.now[:success] = '履歴を更新しました'
      branching_route
    else
      flash.now[:error] = '入力情報に誤りがあります'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    destination = @history.destination
    case @route
    when 'goal_page'
      redirect_to new_history_path(destination: destination.uuid), flash: { success: '履歴を削除しました' }, status: :see_other
    when 'profile_page'
      flash.now[:success] = '履歴を削除しました'
      render turbo_stream: turbo_stream.replace("history_#{@history.uuid}", partial: 'shared/toast')
    when 'moving_page'
      redirect_to new_history_path(destination: destination.uuid), flash: { success: '取り消しました' }, status: :see_other
    end

    @history.destroy!
  end

  def cancel
    branching_route
  end

  private

  def set_history
    @history = current_user.histories.find_by!(uuid: params[:id])
  end

  def set_route
    @route = params[:route]
  end

  def branching_route
    case @route
    when 'goal_page'
      render :show
    when 'profile_page'
      render :cancel
    end
  end

  def history_params
    params.require(:history).permit(:start_time, :end_time, :comment, :moving_distance)
  end
end

app/views/histories/_destination.html.erb
<%= turbo_frame_tag "destination_#{destination_info[:uuid]}" do %>
  <%= render 'shared/toast' if is_turbo_frame_request? %> <%# destinations#createで保存するを選択、destinations#update場合用 %>

  <div class="info-card pb-0 keep-all zen-kaku-regular">
    <div class="text-left mb-1 lg:mb-0 text-gray-700">
      <p class="mr-0 lg:mr-3 block lg:inline-block">
        <%= fa_icon 'floppy-o' %>
        <span class="ml-1">
          <% if destination_info[:created_at] %>
            <%= l(destination_info[:created_at], format: :short) %>
          <% else %>
            未保存
          <% end %>
        </span>
      </p>

      <p class="block lg:inline-block tracking-tighter">
        <%= fa_icon 'home' %>
        <span><%= departure_info[:name] %></span>
      </p>
    </div>

    <div class="text-gray-800 text-2xl lg:text-3xl zen-kaku-medium">
      <h5 class="mr-0 lg:mr-5 block lg:inline-block tracking-tighter">
        <%= fa_icon 'flag' %>
        <%= destination_info[:name] %>
      </h5>

      <h5 class="block sm:inline-block">
        <%= fa_icon 'road' %>
        <%= destination_info[:distance] %>m
      </h5>
    </div>

    <p class="text-gray-700 tracking-tighter"><%= destination_info[:address] %></p>

    <% if !destination_info[:comment].blank? && destination_info[:uuid] %>
      <p class="text-gray-800 tracking-tighter">
        <% if destination_info[:is_published_comment] %>
          <%= fa_icon 'eye' %>
        <% else %>
          <%= fa_icon 'eye-slash' %>
        <% end %>

        <%= fa_icon 'commenting' %>
        <%= destination_info[:comment] %>
      </p>
    <% end %>

    <% if destination_info[:uuid] %>
      <div data-controller="dropdown">
        <%= render 'shared/dropdown' %>

        <div class="mb-3 hidden" data-dropdown-target="menu">
          <%= link_to '編集', edit_destination_path(destination_info[:uuid], route: 'start_page'),
          class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular mr-4' %>

          <%= link_to '削除', destination_path(destination_info[:uuid], route: 'start_page'),
          data: { turbo_method: :delete, turbo_frame: '_top', turbo_confirm: "保存を取り消します\nよろしいですか?"},
          class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular border-red-600 text-red-600' %>
        </div>
      </div>
    <% else %>
      <div class="mb-3"></div>
    <% end %>
  </div>
<% end %>

app/views/histories/_form.html.erb
<div class="text-center my-5">
  <%= link_to 'スタート(片道)', '#',
  data: { turbo_method: :post },
  class: 'orange-btn tracking-widest text-xl px-12 py-3 sm:mr-12 zen-kaku-medium mb-5 sm:mb-0 block sm:inline-block' %>

  <%= link_to 'スタート(往復)', '#',
  data: { turbo_method: :post },
  class: 'orange-btn tracking-widest text-xl px-12 py-3 zen-kaku-medium block sm:inline-block' %>
</div>

app/views/histories/_goal_button.html.erb
<div class="mt-3 text-gray-800 text-2xl lg:text-3xl tracking-wider zen-kaku-bold">
  <h5 class="block lg:inline-block underline decoration-double decoration-sky-600">
        <%= 'START: ' + l(history.start_time, format: :short) %>
  </h5>

  <div class="mt-4 mb-3">
    <%= link_to 'ゴール', history_path(history.uuid),
    data: { turbo_method: :patch },
    class: 'orange-btn tracking-widest text-xl px-12 py-2.5 mx-4 sm:mr-12 sm:mx-0 zen-kaku-medium mb-5 sm:mb-0 block sm:inline-block' %>

    <%= link_to 'やめる', history_path(history.uuid, route: 'moving_page'),
    data: { turbo_method: :delete, turbo_confirm: "スタート記録は削除されます。\nよろしいですか？", turbo_frame: '_top' },
    class: 'border-orange-btn tracking-widest text-xl px-12 py-2.5 mx-4 sm:mx-0 zen-kaku-medium block sm:inline-block' %>
  </div>
</div>

app/views/histories/_history.html.erb
<div class="info-card keep-all zen-kaku-regular">
  <div class="text-left mb-1 lg:mb-0 text-gray-700">
    <p class="block lg:inline-block tracking-tighter">
      <%= fa_icon 'home' %>
      <%= history.departure.name %>
    </p>
  </div>

  <div class="text-gray-800 text-2xl lg:text-3xl zen-kaku-medium">
    <h5 class="mr-0 lg:mr-5 block lg:inline-block tracking-tighter">
      <%= fa_icon 'flag' %>
      <%= history.destination.name %>
    </h5>

    <h5 class="block lg:inline-block">
      <%= fa_icon 'road' %>
      <%= history.moving_distance %>m
    </h5>
  </div>

  <p class="text-gray-700 tracking-tighter"><%= history.destination.address %></p>

  <% if history.comment %>
    <p class="text-gray-800 tracking-tighter">
      <%= fa_icon 'eye-slash' %>
      <%= fa_icon 'commenting' %>
      <%= history.comment %>
    </p>
  <% end %>

  <% if history.end_time %>
    <%= turbo_frame_tag 'goal-field' do %> <%# ゴールした時、差し替わるturbo_frame %>
      <%= render 'shared/toast' if is_turbo_frame_request? %> <%# ゴールした時用 %>
      <%= render 'time', history: history %>
      <div data-controller="dropdown">
        <%= render 'shared/dropdown' %>

        <div class="mb-3 hidden" data-dropdown-target="menu">
          <%= link_to '編集', edit_history_path(history.uuid, route: 'goal_page'),
          data: { turbo_frame: "history_#{history.uuid}" },
          class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular mr-4' %>

          <%= link_to '削除', history_path(history.uuid, route: 'goal_page'),
          data: { turbo_frame: '_top', turbo_method: :delete, turbo_confirm: "履歴から削除します\nよろしいですか?"},
          class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular border-red-600 text-red-600' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= turbo_frame_tag 'goal-field' do %> <%# 未ゴールの際、表示 %>
      <%= render 'goal_button', history: history %>
    <% end %>
  <% end %>
</div>

app/views/histories/_start_button.html.erb
<div class="text-center my-5">
  <%= link_to 'スタート(片道)', histories_path(course: 'one_way'),
  data: { turbo_method: :post },
  class: 'orange-btn tracking-widest text-xl px-12 py-3 mx-4 sm:mr-12 sm:mx-0 zen-kaku-medium mb-5 sm:mb-0 block sm:inline-block' %>

  <%= link_to 'スタート(往復)', histories_path(course: 'round_trip'),
  data: { turbo_method: :post },
  class: 'orange-btn tracking-widest text-xl px-12 py-3 mx-4 sm:mx-0 zen-kaku-medium block sm:inline-block' %>
</div>

app/views/histories/_time.html.erb
<div class="mt-3 text-gray-800 text-2xl lg:text-3xl tracking-wider zen-kaku-bold">
  <h5 class="block lg:inline-block underline decoration-double decoration-sky-600">
    <%= 'START: ' + l(history.start_time, format: :short) %>
  </h5>

  <h5 class="block lg:inline-block ml-0 lg:ml-4 underline decoration-double decoration-teal-600">
    <%= 'GOAL: ' + l(history.end_time, format: :short) %>
  </h5>

  <div class="mt-3 zen-kaku-regular text-xl underline">
    <%= link_to 'ユーザーページに戻る', profile_path, data: { turbo_frame: '_top' } %>
  </div>
</div>

app/views/histories/cancel.html.erb
<div class="info-card pb-0 keep-all zen-kaku-regular">
  <%= render 'profiles/history', history: @history %>
</div>

app/views/histories/edit.html.erb
<div class="basic-card zen-kaku-regular">
  <%= turbo_frame_tag "history_#{@history.uuid}" do %> <%# profile#showから履歴カードを入れ替える用 %>
    <div class="info-card pb-0">
      <%= render 'shared/toast' if is_turbo_frame_request? %> <%# history#updateのバリデーションエラー用 %>

      <%= form_with model: @history, url: history_path(@history.uuid, route: @route), class: 'zen-kaku-medium text-left' do |f| %>
        <div class="my-5">
          <%= f.label :start_time %>
          <%= f.datetime_field :start_time, value: @history.start_time&.strftime('%Y-%m-%d %H:%M') , class: 'normal-form' %>
          <%= render partial: 'shared/error_message', collection: @history.errors.full_messages_for(:start_time) %>
        </div>

        <div class="my-5">
          <%= f.label :end_time %>
          <%= f.datetime_field :end_time, value: @history.end_time&.strftime('%Y-%m-%d %H:%M'), class: 'normal-form'%>
          <%= render partial: 'shared/error_message', collection: @history.errors.full_messages_for(:end_time) %>
        </div>

        <div class="my-5">
          <%= f.label :comment %>
          <%= f.text_area :comment, class: 'normal-form h-32', placeholder: '空白でも可' %>
          <%= render partial: 'shared/error_message', collection: @history.errors.full_messages_for(:comment) %>
        </div>

        <div class="my-5">
          <%= f.label :moving_distance %>
          <%= f.number_field :moving_distance, class: 'normal-form' %>
          <%= render partial: 'shared/error_message', collection: @history.errors.full_messages_for(:moving_distance) %>
        </div>

        <div class="my-5 text-right zen-kaku-regular text-xl tracking-wider">
          <%= link_to '取消', cancel_history_path(@history.uuid, route: @route), class: 'border-orange-btn px-5 py-2' %>
          <%= f.submit '更新', class: 'orange-btn px-5 py-2.5' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/histories/new.html.erb
<% content_for(:title, 'スタート') %>

<div id="map"></div>

<%= turbo_frame_tag 'record-field' do %> <%# destinations#newから遷移してきた時、差し替わるturbo_frame %>
  <%= turbo_frame_tag 'start-field', data: { turbo_action: :advance } do %>
    <%= render 'destination', departure_info: @departure_info, destination_info: @destination_info %>
    <div data-controller="delete" data-action="turbo:before-render@window->delete#oneWayDistance"></div> <%# destinations#newから遷移してきた時、片道の距離を削除する %>
    <%= render 'start_button' %>
  <% end %>
<% end %>

<%= include_gon %>

<% # 表示されているMapのテストは一旦保留するため、読み込まない %>
<% unless Rails.env.test? %>
  <%= javascript_include_tag Settings.google.map_url + 'callback=showRoute', defer: 'defer' %>
<% end %>

app/views/histories/one.html.erb
<div class="info-card pb-0 keep-all zen-kaku-regular">
  <%= render 'profiles/history', history: @history %>
</div>

app/views/histories/show.html.erb
<% content_for(:title, (@history.end_time ? '履歴詳細' : '移動中')) %>

<div id="map"></div>

<%= turbo_frame_tag 'start-field' do %> <%# histories#newから遷移してきた時、差し替わるturbo_frame %>
  <%= turbo_frame_tag "history_#{@history.uuid}" do %>
    <%= render 'shared/toast' if is_turbo_frame_request? && @history.end_time.nil? %> <%# histories#createでスタートして遷移してきた用 %>
    <%= render @history %>
  <% end %>
<% end %>

<%= include_gon %>

<% # 表示されているMapのテストは一旦保留するため、読み込まない %>
<% unless Rails.env.test? %>
  <%= javascript_include_tag Settings.google.map_url + 'callback=showRoute', defer: 'defer' %>
<% end %>