config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'top', to: 'homes#top'
  get 'terms', to: 'homes#terms'

  resources :guests, only: %i[index new]

  get 'signup', to: 'users#new'
  resources :users, only: %i[create]
  resource :profile, only: %i[show edit update destroy] do
    get 'cancel'
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :searches, only: %i[index new create]
  resources :departures
  root 'departures#new'
  resources :destinations, only: %i[new create show edit update destroy]
  resources :histories, only: %i[new create show edit update destroy] do
    get 'cancel', on: :member
  end
end

app/models/departure.rb
class Departure < ApplicationRecord
  has_many :destinations, dependent: :destroy
  belongs_to :user
  belongs_to :location, dependent: :destroy

  validates :is_saved, inclusion: { in: [true, false] }

  before_create -> { self.uuid = SecureRandom.uuid }

  delegate :name, :latitude, :longitude, :address, :place_id, to: :location

  scope :saved, -> { where(is_saved: true) }
  scope :with_location, -> { includes(:location) }
  scope :recent, -> { order(created_at: :desc) }

  scope :saved_list, -> { saved.with_location.recent }

  def self.create_with_location(user, departure_info)
    location = Location.create_from_info(departure_info)
    create_from_info(user, location, departure_info)
  end

  def self.create_from_info(user, location, departure_info)
    attribute_symboles = departure_info.slice(:is_saved)
    attributes_for_create = { user:, location: }.merge(attribute_symboles)
    create!(attributes_for_create)
  end

  def attributes_for_session
    { uuid:, name:, latitude:, longitude:, address:, place_id:, created_at: }
  end

  # departure_form
  def attributes_for_form
    { name:, address: }
  end
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  before_action :set_departure_and_location, only: %i[show edit update destroy]

  def index
    @departures = current_user.departures.saved_list
    @destinations = current_user.destinations.saved_list
  end

  def show; end

  def new
    @departure_form = DepartureForm.new
    set_saved_departures_and_histories
  end

  def edit
    @departure_form = DepartureForm.new(@departure.attributes_for_form)
  end

  def create
    @departure_form = DepartureForm.new(departure_form_params)
    return render_new_departure('入力情報に誤りがあります') unless @departure_form.valid?(:check_save)

    result = Api::GeocodeService.new(@departure_form).call
    return render_new_departure('位置情報の取得に失敗しました') unless result

    if result[:is_saved]
      departure = Departure.create_with_location(current_user, result)
      session[:departure] = departure.attributes_for_session
      flash[:success] = '出発地を保存しました'
    else
      session[:departure] = result
    end

    redirect_to new_search_path
  end

  def update
    @departure_form = DepartureForm.new(edit_departure_form_params)
    return render_edit_departure('入力情報に誤りがあります') unless @departure_form.valid?

    if @location.address == @departure_form.address
      @location.update!(edit_departure_form_params)
    else
      result = Api::GeocodeService.new(@departure_form).call
      return render_edit_departure('位置情報の取得に失敗しました') unless result

      @location.update!(result.compact)
    end

    redirect_to departure_path(@departure.uuid), flash: { success: '出発地を更新しました' }
  end

  def destroy
    @departure.update!(is_saved: false)
    flash.now[:success] = '出発地を保存済みから削除しました'
    render turbo_stream: turbo_stream.replace("departure_#{@departure.uuid}", partial: 'shared/toast')
  end

  private

  def set_saved_departures_and_histories
    @departures = current_user.departures.saved_list
    @histories = current_user.histories.finished_list
  end

  def set_departure_and_location
    @departure = current_user.departures.find_by!(uuid: params[:id])
    @location = @departure.location
  end

  def render_new_departure(error_message)
    set_saved_departures_and_histories
    flash.now[:error] = error_message
    render :new, status: :unprocessable_entity
  end

  def render_edit_departure(error_message)
    flash.now[:error] = error_message
    render :edit, status: :unprocessable_entity
  end

  def departure_form_params
    params.require(:departure_form).permit(:name, :address, :is_saved)
  end

  def edit_departure_form_params
    params.require(:departure_form).permit(:name, :address)
  end
end

app/controllers/search/departures_controller.rb
class Search::DeparturesController < ApplicationController
  def new
    @departure_form = DepartureForm.new
    set_saved_departures_and_histories
  end

  def create
    @departure_form = DepartureForm.new(departure_form_params)
    result = RequestGeocodeService.new(@departure_form).call

    if result.include?(:error)
      set_saved_departures_and_histories
      flash.now[:error] = result[:error]
      return render :new, status: :unprocessable_entity
    end

    result_of_create_departure = CreateDepartureService.new(current_user, result, @departure_form.is_saved).call
    session[:departure] = result_of_create_departure[:departure]
    redirect_to new_search_destination_path, flash: {success: result_of_create_departure[:success]}
  end

  private

  def departure_form_params
    params.require(:departure_form).permit(:name, :address, :is_saved)
  end

  def set_saved_departures_and_histories
    @departures = current_user.departures.saved_list
    @histories = current_user.histories.finished_list
  end
end

app/views/departures/_departure.html.erb
<%= turbo_frame_tag "departure_#{departure.uuid}" do %> <%# departure#index, newにて、1つ1つに割り振る用 %>
  <div class="info-card pb-0 keep-all zen-kaku-regular">
    <%= render 'shared/toast' if is_turbo_frame_request? %> <%# departure#update成功用 %>

    <p class="mb-1.5 text-left text-gray-700">
      <%= fa_icon 'floppy-o' %>
      <span class="ml-1"><%= l(departure.created_at, format: :short) %></span>
    </p>

    <h5 class="mb-1 text-2xl lg:text-3xl text-gray-800 zen-kaku-medium tracking-tighter">
      <%= departure.name %>
    </h5>

    <p class="mb-3 text-gray-700 tracking-tighter">
      <%= departure.address %>
    </p>

    <div>
      <%= link_to '出発', new_search_path(departure: departure.uuid),
      data: { turbo_frame: '_top' },
      class: 'orange-btn tracking-widest text-xl px-12 py-2 zen-kaku-medium' %>
    </div>

    <div data-controller="dropdown">
      <%= render 'shared/dropdown' %>

      <div class="mb-3 hidden" data-dropdown-target="menu">
        <%= link_to '編集', edit_departure_path(departure.uuid),
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular mr-4' %>
        <%= link_to '削除', departure_path(departure.uuid),
        data: { turbo_method: :delete, turbo_confirm: "保存済みから削除します\nよろしいですか?"},
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular border-red-600 text-red-600' %>
      </div>
    </div>
  </div>
<% end %>

app/views/departures/_destination.html.erb
<%= turbo_frame_tag "destination_#{destination.uuid}" do %> <%# departure#indexにて、1つ1つに割り振る用 %>
  <div class="info-card pb-0 keep-all zen-kaku-regular">
    <%= render 'shared/toast' if is_turbo_frame_request? %> <%# destination#update成功用 %>

    <div class="text-left mb-1 lg:mb-0 text-gray-700">
      <p class="mr-0 lg:mr-3 block lg:inline-block">
        <%= fa_icon 'floppy-o', class: "mr-1"%>
        <%= l(destination.created_at, format: :short) %>
      </p>

      <p class="block lg:inline-block tracking-tighter">
        <%= fa_icon 'home' %>
        <%= destination.departure.name %>
      </p>
    </div>

    <div class="text-gray-800 text-2xl lg:text-3xl zen-kaku-medium">
      <h5 class="mr-0 lg:mr-5 block lg:inline-block tracking-tighter">
        <%= fa_icon 'flag' %>
        <%= destination.name %>
      </h5>

      <h5 class="block sm:inline-block">
        <%= fa_icon 'road' %>
        <%= destination.distance %>m
      </h5>
    </div>

    <p class="text-gray-700 tracking-tighter">
      <%= destination.address %>
    </p>

    <div class="text-gray-800 tracking-tighter mt-0.5 mb-3">
      <% if destination.comment %>
        <p>
          <% if destination.is_published_comment %>
            <%= fa_icon 'eye' %>
          <% else %>
            <%= fa_icon 'eye-slash' %>
          <% end %>

          <%= fa_icon 'commenting' %>
          <%= destination.comment %>
        </p>
      <% end %>
    </div>

    <div>
      <%= link_to '出発', new_history_path(destination: destination.uuid),
      data: { turbo_frame: '_top' },
      class: 'orange-btn tracking-widest text-xl px-12 py-2 zen-kaku-medium' %>
    </div>

    <div data-controller="dropdown">
      <%= render 'shared/dropdown' %>

      <div class="mb-3 hidden" data-dropdown-target="menu">
        <%= link_to '編集', edit_destination_path(destination.uuid, route: 'saved_page'),
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular mr-4' %>
        <%= link_to '削除', destination_path(destination.uuid, route: 'saved_page'),
        data: { turbo_method: :delete, turbo_confirm: "保存済みから削除します\nよろしいですか?"},
        class: 'border-orange-btn tracking-widest text-lg px-8 py-1.5 zen-kaku-regular border-red-600 text-red-600' %>
      </div>
    </div>
  </div>
<% end %>

app/views/departures/_form.html.erb
<%= form_with model: departure_form, url: departures_path, class: 'zen-kaku-medium' do |f| %>
  <div class="my-5">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'normal-form' %>
    <%= render partial: 'shared/error_message', collection: departure_form.errors.full_messages_for(:name) %>
  </div>

  <div class="my-5">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'normal-form' %>
    <%= link_to '現在地取得', '#', class: 'text-blue-600 underline', id: 'js-get-current-location-button' %>
    <p class="hidden" id="js-loading-text">読込中……</p>
    <%= render partial: 'shared/error_message', collection: departure_form.errors.full_messages_for(:address) %>
  </div>

  <div class="my-5">
    <%= f.check_box :is_saved, class: 'p-2 mb-1 mr-3 inline-block shadow rounded-lg border border-gray-300 bg-gray-50' %>
    <%= f.label :is_saved %>
    <%= render partial: 'shared/error_message', collection: departure_form.errors.full_messages_for(:is_saved) %>
  </div>

  <div class="my-5 text-right">
    <%= f.submit '決定', class: 'orange-btn tracking-wider text-xl px-5 py-2.5 zen-kaku-regular' %>
  </div>
<% end %>

app/views/departures/_history.html.erb
<div class="info-card keep-all zen-kaku-regular">
  <p class="text-left text-gray-700">
    <%= fa_icon 'clock-o'%>
    <%= l(history.start_time, format: :short) %>
    <span class="ml-1"><%= history.decorate.moving_time %>分</span>
    <%= fa_icon 'road',  class: 'ml-1'%>
    <%= history.moving_distance %>m
  </p>

  <p class="mb-1.5 text-left text-gray-700 tracking-tighter">
    <%= fa_icon 'flag' %>
    <span><%= history.destination.name %></span>
  </p>

  <h5 class="mb-1 text-2xl lg:text-3xl text-gray-800 zen-kaku-medium tracking-tighter">
    <%= history.destination.departure.name %>
  </h5>

  <p class="mb-3 text-gray-700 tracking-tighter">
    <%= history.destination.departure.address %>
  </p>

  <div class="mt-4 mb-3">
    <%= link_to '出発', new_search_path(departure: history.destination.departure.uuid),
    class: 'orange-btn tracking-widest text-xl px-12 py-2 zen-kaku-medium' %>
  </div>
</div>

app/views/departures/edit.html.erb
<div class="basic-card zen-kaku-regular">
  <%= turbo_frame_tag "departure_#{@departure.uuid}" do %> <%# departure#index, newから出発地カードを入れ替える用 %>
    <%= render 'shared/toast' if is_turbo_frame_request? %> <%# departure#updateのバリデーションエラー用 %>

    <div class="info-card pb-0">
      <%= form_with model: @departure_form, url: departure_path(@departure.uuid), class: 'zen-kaku-medium', method: :patch do |f| %>
        <div class="my-5 text-left">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'normal-form' %>
          <%= render partial: 'shared/error_message', collection: @departure_form.errors.full_messages_for(:name) %>
        </div>

        <div class="my-5 text-left">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'normal-form' %>
          <%= render partial: 'shared/error_message', collection: @departure_form.errors.full_messages_for(:address) %>
        </div>

        <div class="my-5 text-right zen-kaku-regular text-xl tracking-wider">
          <%= link_to '取消', departure_path(@departure.uuid), class: 'border-orange-btn px-5 py-2' %>
          <%= f.submit '更新', class: 'orange-btn px-5 py-2.5' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/departures/index.html.erb
<% content_for(:title, '保存済み出発地/目的地') %>

<h1 class="headline zen-kaku-medium">保存済み</h1>
<div class="tabs">
  <input id="left" type="radio" name="tab-radio-button">
  <label class="tab-item w-1/2 zen-kaku-medium text-xl tracking-widest" for="left">
    <%= fa_icon 'home', class: 'text-2xl' %>
    出発地
  </label>

  <input id="right" type="radio" name="tab-radio-button" checked>
  <label class="tab-item w-1/2 zen-kaku-medium text-xl tracking-widest" for="right">
    <%= fa_icon 'flag', class: 'text-2xl' %>
    目的地
  </label>

  <div class="tab-content" id="left-content">
    <%= render @departures %>
  </div>

  <div class="tab-content relative" id="right-content">
    <%= render partial: 'destination', collection: @destinations %>
  </div>
</div>

app/views/departures/new.html.erb
<% content_for(:title, '出発地を選択') %>

<h1 class="headline zen-kaku-medium">出発地</h1>
<div class="tabs">
  <input id="left" type="radio" name="tab-radio-button" checked>
  <label class="tab-item w-1/3 zen-kaku-bold" for="left">
    <%= fa_icon 'pencil-square-o', class: 'text-2xl' %>
    入力
  </label>

  <input id="center" type="radio" name="tab-radio-button">
  <label class="tab-item w-1/3 zen-kaku-bold border-x-2 border-x-gray-300" for="center">
    <%= fa_icon 'folder-open', class: 'text-2xl' %>
    保存
  </label>

  <input id="right" type="radio" name="tab-radio-button">
  <label class="tab-item w-1/3 zen-kaku-bold" for="right">
    <%= fa_icon 'history', class: 'text-2xl' %>
    履歴
  </label>

  <div class="tab-content" id="left-content">
    <%= render 'form', departure_form: @departure_form %>
  </div>

  <div class="tab-content relative" id="center-content">
    <%= render @departures %>
  </div>

  <div class="tab-content relative" id="right-content">
    <%= render partial: 'history', collection: @histories %>
  </div>
</div>

<% # 現在地取得のテストは一旦保留するため、読み込まない %>
<% unless Rails.env.test? %>
  <%= javascript_include_tag Settings.google.map_url + 'callback=getCurrentLocation', defer: 'defer' %>
<% end %>

app/views/departures/show.html.erb
<div class="info-card pb-0 keep-all zen-kaku-regular">
  <%= render @departure %>
</div>